trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Docker@2
    displayName: Build and Push aloysbaillet/aswf-vfx2018
    inputs:
      command: buildAndPush
      containerRegistry: dockerHubConnection
      repository: aloysbaillet/aswf-vfx2018
      Dockerfile: docker/aswf-vfx2018/Dockerfile
      tags: aloysbaillet/aswf-vfx2018:latest
  - task: Docker@2
    displayName: Build and Push aloysbaillet/aswf-vfx2018-conan
    inputs:
      command: buildAndPush
      containerRegistry: dockerHubConnection
      repository: aloysbaillet/aswf-vfx2018-conan
      Dockerfile: docker/aswf-vfx2018-conan/Dockerfile
      tags: aloysbaillet/aswf-vfx2018-conan:latest
