stages:
- stage: build_docker_images
  displayName: Build and Publish docker images  
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: build_docker_images
    displayName: Build Docker Images
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build and Push aloysbaillet/aswf-vfx2018
      inputs:
        command: buildAndPush
        containerRegistry: dockerHubConnection
        repository: aloysbaillet/aswf-vfx2018
        Dockerfile: docker/aswf-vfx2018/Dockerfile
        tags: |
          latest
          2018
          2018.0
    - task: Docker@2
      displayName: Build and Push aloysbaillet/aswf-vfx2018-conan
      inputs:
        command: buildAndPush
        containerRegistry: dockerHubConnection
        repository: aloysbaillet/aswf-vfx2018-conan
        Dockerfile: docker/aswf-vfx2018-conan/Dockerfile
        tags: |
          latest
          2018
          2018.0

- stage: build_windows_conan_packages
  displayName: Build Windows Conan Packages
  condition: always()
  jobs:
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: TBB
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: boost
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: IlmBase
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: OpenEXR
      inputPackages:
        - IlmBase
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: numpy
  - template: .azure/build-windows-conan-package.yml
    parameters:
      package: PyIlmBase
      inputPackages:
        - IlmBase
        - OpenEXR
        - boost
        - numpy

- stage: build_linux_conan_packages
  displayName: Build Linux Conan Packages
  condition: always()
  jobs:
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: TBB
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: boost
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: numpy
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: IlmBase
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: OpenEXR
      inputPackages:
        - IlmBase
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: PyIlmBase
      inputPackages:
        - IlmBase
        - OpenEXR
        - boost
        - numpy
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: Qt
      timeoutInMinutes: 180
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: PySide
      timeoutInMinutes: 120
      inputPackages:
        - Qt
  - template: .azure/build-linux-conan-package.yml
    parameters:
      package: OpenColorIO

- stage: upload_conan_packages
  displayName: Upload Conan Packages
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: upload_conan_packages
    displayName: Upload Conan Packages
    pool:
      vmImage: 'ubuntu-16.04'
    container: aloysbaillet/aswf-vfx2018-conan:latest
    steps:
    - template: .azure/download-linux-conan-artifact.yml
      parameters:
        packages:
        - TBB
        - boost
        - numpy
        - IlmBase
        - OpenEXR
        - Qt
        - PySide
        - OpenColorIO
    - bash: |
        conan user -p $BINTRAY_API_KEY -r aswftest aloysbaillet
        conan upload "*" -r aswftest --all --force --confirm
      env:
        BINTRAY_API_KEY: $(conan.apiKey)
