version: 2.1

executors:
  aswf-vfx2018-conan:
    docker:
      - image: aloysbaillet/aswf-vfx2018-conan

jobs:
  build-TBB:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: TBB build
          command: conan create conan/TBB aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - TBB

  build-boost:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: boost build
          environment: 
            CONAN_CPU_COUNT: 4 # the default of 36 on circleci makes the jor run out of memory!
          command: conan create conan/boost aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - boost

  build-numpy:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: numpy build
          command: conan create conan/numpy aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - numpy

  deploy:
    executor: aswf-vfx2018-conan

    steps:
      - attach_workspace:
          at: /home/circleci/.conan/data
      - run:
          name: Packages upload
          command: |
            conan user
            conan upload TBB/*@aswf/vfx2018 --force --confirm --all -r=aswftest
            conan upload boost/*@aswf/vfx2018 --force --confirm --all -r=aswftest
            conan upload numpy/*@aswf/vfx2018 --force --confirm --all -r=aswftest

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build-TBB
      - build-boost
      - build-numpy
      - deploy:
          requires:
            - build-TBB
            - build-boost
            - build-numpy
          filters:
            branches:
              only: master
