version: 2.1

executors:
  aswf-vfx2018-conan:
    docker:
      - image: aloysbaillet/aswf-vfx2018-conan

jobs:
  build-docker-images:
    machine: true
    steps:
      - checkout
      # login docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the base image
      - run: docker build docker/aswf-vfx2018 -t aloysbaillet/aswf-vfx2018
      # deploy the base image
      - run: docker push aloysbaillet/aswf-vfx2018
      # build the conan image
      - run: docker build docker/aswf-vfx2018-conan -t aloysbaillet/aswf-vfx2018-conan
      # deploy the conan image
      - run: docker push aloysbaillet/aswf-vfx2018-conan

  build-TBB:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: TBB build
          environment: 
            CONAN_PRINT_RUN_COMMANDS: 1
            CONAN_LOGGING_LEVEL: 10 # debug
          command: conan create conan/TBB aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - TBB

  build-boost:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: boost build
          environment: 
            CONAN_PRINT_RUN_COMMANDS: 1
            CONAN_LOGGING_LEVEL: 10 # debug
            CONAN_CPU_COUNT: 4 # the default of 36 on circleci makes the jor run out of memory!
          command: conan create conan/boost aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - boost

  build-numpy:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: numpy build
          command: conan create conan/numpy aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - numpy

  build-Qt:
    executor: aswf-vfx2018-conan

    steps:
      - checkout

      - run:
          name: Qt build
          environment: 
            CONAN_CPU_COUNT: 8 # the default of 36 on circleci makes the jor run out of memory!
            PARALLEL_JOBS: 4 # limit for qt build
            NINJAFLAGS: -j8
          command: conan create conan/Qt aswf/vfx2018

      - persist_to_workspace:
          root: /home/circleci/.conan/data
          paths:
            - Qt

  deploy:
    executor: aswf-vfx2018-conan

    steps:
      - attach_workspace:
          at: /home/circleci/.conan/data
      - run:
          name: Packages upload
          command: |
            conan user
            conan upload TBB/*@aswf/vfx2018 --force --confirm --all -r=aswftest
            conan upload boost/*@aswf/vfx2018 --force --confirm --all -r=aswftest
            conan upload numpy/*@aswf/vfx2018 --force --confirm --all -r=aswftest
            conan upload Qt/*@aswf/vfx2018 --force --confirm --all -r=aswftest

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build-docker-images:
          filters:
            branches:
              only: master
      - build-TBB:
          requires:
            - build-docker-images
      - build-boost:
          requires:
            - build-docker-images
      - build-numpy:
          requires:
            - build-docker-images
      - build-Qt:
          requires:
            - build-docker-images
      - deploy:
          requires:
            - build-TBB
            - build-boost
            - build-numpy
            - build-Qt
          filters:
            branches:
              only: master
