parameters:
  package: ""
  conan_cpu_count: 2
  inputPackages: []
  timeoutInMinutes: 60
jobs:
- job: build_${{ parameters.package }}
  displayName: Build ${{ parameters.package }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  pool:
    vmImage: 'ubuntu-16.04'
  container: aloysbaillet/aswf-vfx2018-conan:latest
  dependsOn:
    - ${{ each pkg in parameters.inputPackages }}:
      - build_${{ pkg }}
  steps:
    - ${{ each pkg in parameters.inputPackages }}:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'conan_data_${{ pkg }}'
          targetPath: 'conan_data_${{ pkg }} '
      - bash: mkdir -p /tmp/.conan/data && mv conan_data_${{ pkg }} /tmp/.conan/data/${{ pkg }}
        displayName: Moving ${{ pkg }} artifact to conan cache
    - bash: conan create conan/${{ parameters.package }} aswf/vfx2018
      displayName: Build ${{ parameters.package }}
      env: 
        CONAN_PRINT_RUN_COMMANDS: 1
        CONAN_LOGGING_LEVEL: 10 # debug
        CONAN_CPU_COUNT: ${{ parameters.conan_cpu_count }}
    - bash: mv /tmp/.conan/data/${{ parameters.package }} conan_data_${{ parameters.package }}
      displayName: Moving ${{ parameters.package }} conan cache to artifact
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'conan_data_${{ parameters.package }}'
        targetPath: 'conan_data_${{ parameters.package }}'
