parameters:
  package: ""
  conan_cpu_count: 2
  inputPackages: []
  timeoutInMinutes: 60
jobs:
- job: build_${{ parameters.package }}
  displayName: Build ${{ parameters.package }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  pool:
    vmImage: 'vs2017-win2016'
  dependsOn:
    - ${{ each pkg in parameters.inputPackages }}:
      - build_${{ pkg }}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        addToPath: true 
        architecture: 'x64'

    - script: python -m pip install conan
      displayName: 'Install Conan'

    - bash: conan config install conan/config/windows-vfx-2018
      displayName: 'Configure Conan'

    - bash: conan create conan/${{ parameters.package }} aswf/vfx2018
      displayName: Build ${{ parameters.package }}
      env: 
        CONAN_PRINT_RUN_COMMANDS: 1
        CONAN_LOGGING_LEVEL: 10 # debug
        CONAN_CPU_COUNT: ${{ parameters.conan_cpu_count }}

    - bash: 
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'windows_conan_data_${{ parameters.package }}'
        targetPath: 'C:/Users/VssAdministrator/.conan/data/${{ parameters.package }}'
